#!/bin/sh

cd $(dirname $0)

if [ ! -e $HOME/.zshenv ]; then
  cp $PWD/.zshenv $HOME/.zshenv
elif ! grep -q 'export ZDOTDIR=$XDG_CONFIG_HOME/zsh' $HOME/.zshenv ; then
  cat $PWD/.zshenv >> $HOME/.zshenv
fi
